### ISSUE TITLE
"Your Stellar Address loading" on fresh Play Store install

### ISSUE THREAD

**Issue by eturpin** [TbLtzk/Centaurus#80]
Just installed Centaurus from the Google Play Store, and when I go to the receive tab, at the top it says "Your Stellar Address loading", and has a QR code underneath. I'm guessing my public key should be displayed instead of the word "loading."

This is a fresh install, I have no XLM, trust lines, anchors, etc.

About says I have version 2.5.

Using Android 5.0

**Comment by TbLtzk** [comment]
Hmm, this is weird! This used to happen on some devices in the past, but only on older android versions. Which device is it? In the wallet tab, do you see this symbol confirming you have network access? 
![image](https://cloud.githubusercontent.com/assets/8383712/25143689/a62133be-246b-11e7-8f6b-cc9d925f90f9.png)

**Comment by tdiv7653** [comment]
Hello, I actually have the same exact issue since fresh install about 24 hrs ago.  Same version of app and Droid turbo system.  I can see the bars on wallet tab however they are greyed out which tells me that the app is not reaching internet despite allowing permissions.  No address to receive just the "loading".

**Comment by TbLtzk** [comment]
I'm really sorry for the issue! It only affects new users. And of course all my alpha and beta testers have already accounts created. Hope this fixes it. Will be released in version 2.5.1 in a few days.
